export const routes = ['Home','Photos','Files','Transfers','Storage','Remote','Browser','YouTube','Music','Notes','Calculator','Devices','Hardware','Settings'];
export const icons = ['⌂','▧','▤','⇄','◴','⌘','◎','▶','♫','✎','+','▣','⚙','☷'];
const hi = {
  'Fullscreen':'पूर्ण स्क्रीन','Up next':'अगले गीत','Queue is empty':'कतार खाली है','Add to queue':'कतार में जोड़ें','This track could not be played.':'यह गीत नहीं चल सका।','Clear history':'इतिहास मिटाएँ',
  'Website requested':'वेबसाइट ने अनुरोध किया','Grant permission and retry the website action.':'अनुमति दें और वेबसाइट में फिर कोशिश करें।','Private playlists are available in the installed Windows app.':'निजी प्लेलिस्ट इंस्टॉल किए हुए Windows ऐप में उपलब्ध हैं।',
  'YouTube opens in a separate private website session. If playback or sign-in is unsupported by WebView2, use your installed browser.':'YouTube अलग निजी विंडो में खुलता है। यदि WebView2 पर वीडियो या साइन-इन काम न करे, तो इंस्टॉल किया हुआ ब्राउज़र इस्तेमाल करें।',
  'Similar photos':'मिलती-जुलती तस्वीरें',
  'Scan for similar photos':'मिलती-जुलती तस्वीरें खोजें',
  'These are suggestions only. No photos are removed automatically.':'ये केवल सुझाव हैं। कोई तस्वीर अपने आप नहीं हटाई जाती।',
  'Address or search':'पता या खोज',
  'Searches open DuckDuckGo in a separate website window.':'खोज DuckDuckGo की अलग वेबसाइट विंडो में खुलती है।',
  'Restore previous tabs':'पिछले टैब फिर खोलें',
  'Private apps ready':'निजी ऐप तैयार हैं',
  'Private app trash':'निजी ऐप का कूड़ेदान','note':'नोट','playlist':'प्लेलिस्ट','bookmark':'बुकमार्क',
  'Expression is too long.':'गणना बहुत लंबी है।','Result is outside the supported range.':'परिणाम समर्थित सीमा से बाहर है।','Too many brackets.':'बहुत अधिक कोष्ठक हैं।','Close the bracket.':'कोष्ठक बंद करें।','Enter a number.':'संख्या दर्ज करें।','Expression is too complex.':'गणना बहुत जटिल है।','Cannot divide by zero.':'शून्य से भाग नहीं कर सकते।','Use numbers, brackets and arithmetic operators only.':'केवल संख्या, कोष्ठक और गणना चिह्न इस्तेमाल करें।',
  'Open the installed Windows app to use private apps and browser controls.':'निजी ऐप और ब्राउज़र नियंत्रण के लिए इंस्टॉल किया हुआ Windows ऐप खोलें।','Open the installed app, or unlock this dashboard with your local session key.':'इंस्टॉल किया हुआ ऐप खोलें या स्थानीय सत्र कुंजी से यह डैशबोर्ड खोलें।','Download cancelled':'डाउनलोड रद्द किया गया','Download stalled. Try again.':'डाउनलोड रुक गया। फिर कोशिश करें।','Download was interrupted':'डाउनलोड बीच में रुक गया','Download was incomplete':'डाउनलोड अधूरा था','Home Hub is not reachable. Start the service and try again.':'Home Hub उपलब्ध नहीं है। सेवा शुरू करके फिर कोशिश करें।','This format cannot be previewed here. Download it to open in another app.':'इस फ़ॉर्मेट का प्रीव्यू यहाँ उपलब्ध नहीं है। दूसरे ऐप में खोलने के लिए डाउनलोड करें।',
  'open':'चल रहा है','queued':'कतार में','running':'चल रहा है','verifying':'सत्यापित हो रहा है','complete':'पूरा','completed':'पूरा','failed':'विफल','cancelled':'रद्द','downloading':'डाउनलोड हो रहा है','active':'सक्रिय','revoked':'हटाया गया','send':'भेजें','receive':'प्राप्त करें','sending':'भेज रहा है','receiving':'प्राप्त कर रहा है','import':'आयात','library_move':'लाइब्रेरी स्थान बदलें','copy':'कॉपी','scrub':'फ़ाइलों की जाँच','second_copy':'दूसरी कॉपी',
  'Categories':'श्रेणियाँ','Free Bytes':'खाली जगह (बाइट)','Total Bytes':'कुल जगह (बाइट)','Copies':'कॉपी','Disks':'ड्राइव','Health':'स्थिति','Model':'मॉडल','Temperature C':'तापमान (°C)','Disk Id':'ड्राइव पहचान','Cpu':'CPU','Ram':'RAM','Ratings':'क्षमता','Network':'नेटवर्क','Helper Available':'सहायक उपलब्ध','Remote Enabled':'रिमोट सक्षम','Originals Preserved':'मूल फ़ाइलें सुरक्षित','Restart Required':'फिर शुरू करना आवश्यक','Files':'फ़ाइलें','Bytes':'बाइट','Default Choice':'डिफ़ॉल्ट विकल्प','Path':'पथ','good':'अच्छा','caution':'सावधानी','failing':'समस्या','unknown':'अज्ञात','State':'स्थिति','Owner':'मालिक',
  'Start Cast on your phone to show its screen on this laptop. Video only; the phone keeps control.':'लैपटॉप पर फ़ोन की स्क्रीन दिखाने के लिए फ़ोन पर Cast शुरू करें। केवल वीडियो दिखेगा; नियंत्रण फ़ोन पर रहेगा।',
  'Changing permissions resets this tab’s website session and reloads the page.':'अनुमति बदलने से इस टैब का वेबसाइट सत्र रीसेट होगा और पेज फिर लोड होगा।',
  'Home':'होम','Photos':'फ़ोटो','Files':'फ़ाइलें','Transfers':'ट्रांसफ़र','Storage':'स्टोरेज','Remote':'रिमोट','Browser':'ब्राउज़र','YouTube':'यूट्यूब','Music':'संगीत','Notes':'नोट्स','Calculator':'कैलकुलेटर','Devices':'डिवाइस','Hardware':'हार्डवेयर','Settings':'सेटिंग्स',
  'Refresh':'रिफ़्रेश','Save':'सहेजें','Cancel':'रद्द करें','Close':'बंद करें','Search':'खोजें','Name':'नाम','Status':'स्थिति','Size':'आकार','Download':'डाउनलोड','Trash':'कूड़ेदान','Restore':'वापस लाएँ','Rename':'नाम बदलें','Move':'ले जाएँ','Copy':'कॉपी','Next':'अगला','Back':'पीछे','Later':'बाद में','Keep in place':'यहीं रखें','Import a copy':'कॉपी आयात करें','Scan folders':'फ़ोल्डर जाँचें','Folder paths (one per line)':'फ़ोल्डर पथ (हर पंक्ति में एक)','Original files stay where they are.':'मूल फ़ाइलें अपनी जगह पर रहेंगी।','Nothing here yet.':'अभी यहाँ कुछ नहीं है।',
  'Your private home cloud':'आपका निजी होम क्लाउड','Connected locally':'स्थानीय कनेक्शन','Service unavailable':'सेवा उपलब्ध नहीं','Pause sharing':'साझा करना रोकें','Resume sharing':'साझा करना शुरू करें','Pair a device':'डिवाइस जोड़ें','Free space':'खाली जगह','Connected devices':'जुड़े हुए डिवाइस','Active transfers':'चल रहे ट्रांसफ़र','Alerts':'सूचनाएँ','A single drive is not a backup.':'एक ड्राइव बैकअप नहीं है।','Welcome to Home Hub':'Home Hub में आपका स्वागत है','Set up your home':'अपना होम सेट करें','Hub name':'हब का नाम','Library folder':'लाइब्रेरी फ़ोल्डर','Second-copy folder':'दूसरी कॉपी का फ़ोल्डर','Protect your memories':'अपनी यादें सुरक्षित करें','Choose an external drive for a second copy.':'दूसरी कॉपी के लिए बाहरी ड्राइव चुनें।','Turn on BitLocker in Windows to protect data at rest.':'डेटा सुरक्षित रखने के लिए Windows में BitLocker चालू करें।','Finish setup':'सेटअप पूरा करें','Optional':'वैकल्पिक','Private apps are available in the installed Windows app.':'निजी ऐप इंस्टॉल किए हुए Windows ऐप में उपलब्ध हैं।','Open the installed app':'इंस्टॉल किया हुआ ऐप खोलें',
  'New note':'नया नोट','Untitled note':'बिना शीर्षक का नोट','Note title':'नोट का शीर्षक','Note text':'नोट का टेक्स्ट','Saving…':'सहेजा जा रहा है…','Saved':'सहेजा गया','Export Markdown':'Markdown निर्यात','Export text':'टेक्स्ट निर्यात','Import note':'नोट आयात','Private to this Windows user. Autosaves offline.':'इस Windows उपयोगकर्ता के लिए निजी। ऑफ़लाइन अपने आप सहेजा जाता है।','Export private apps':'निजी ऐप निर्यात','Import private apps':'निजी ऐप आयात','New playlist':'नई प्लेलिस्ट','Playlist name':'प्लेलिस्ट का नाम','Add to playlist':'प्लेलिस्ट में जोड़ें','Remove':'हटाएँ','Play':'चलाएँ','Previous':'पिछला','Shuffle':'शफ़ल','Repeat':'दोहराएँ','All music':'सारा संगीत',
  'Website address':'वेबसाइट का पता','Open website':'वेबसाइट खोलें','Open in default browser':'डिफ़ॉल्ट ब्राउज़र में खोलें','Bookmarks':'बुकमार्क','Bookmark':'बुकमार्क करें','Tabs':'टैब','Reload':'फिर लोड करें','Focus':'सामने लाएँ','Website permissions':'वेबसाइट अनुमतियाँ','Allow downloads':'डाउनलोड की अनुमति','camera':'कैमरा','microphone':'माइक्रोफ़ोन','location':'स्थान','notifications':'सूचनाएँ','protected_media':'सुरक्षित मीडिया','Clear website data':'वेबसाइट डेटा मिटाएँ','Internet required. Website windows cannot access Home Hub or private apps.':'इंटरनेट आवश्यक है। वेबसाइट विंडो Home Hub या निजी ऐप तक नहीं पहुँच सकतीं।','YouTube opens in a separate private website session.':'YouTube एक अलग निजी वेबसाइट सत्र में खुलता है।',
  'Language':'भाषा','Larger text':'बड़ा टेक्स्ट','High contrast':'अधिक कंट्रास्ट','Reduce motion':'कम एनीमेशन','Enable remote control':'रिमोट नियंत्रण सक्षम करें','Remote is off until you grant a device permission.':'डिवाइस को अनुमति देने तक रिमोट बंद रहता है।','Device permissions':'डिवाइस अनुमतियाँ','Revoke device':'डिवाइस हटाएँ','Approve':'स्वीकार करें','Deny':'अस्वीकार करें','Manual code':'मैन्युअल कोड','Pairing expires in':'जोड़ने का समय शेष','seconds':'सेकंड','Phone storage cleanup requires verified copies and confirmation on your phone.':'फ़ोन स्टोरेज साफ़ करने के लिए सत्यापित कॉपी और फ़ोन पर पुष्टि आवश्यक है।','Run integrity check':'फ़ाइलों की जाँच करें','Create second copy':'दूसरी कॉपी बनाएँ','Jobs':'कार्य','Move library':'लाइब्रेरी स्थान बदलें','Review duplicates':'डुप्लिकेट देखें','Diagnostics export':'डायग्नोस्टिक्स निर्यात','Run hardware check':'हार्डवेयर जाँचें','Wake support varies by laptop. Files stay queued when the Hub is asleep.':'लैपटॉप के अनुसार वेक समर्थन बदलता है। हब सोते समय फ़ाइलें कतार में रहती हैं।','Local session key':'स्थानीय सत्र कुंजी','Unlock dashboard':'डैशबोर्ड खोलें','No secret is included in this page. Use the installed app, or enter its local session key.':'इस पेज में कोई गुप्त कुंजी नहीं है। इंस्टॉल किया हुआ ऐप खोलें या उसकी स्थानीय सत्र कुंजी दर्ज करें।',
  'Confirm':'पुष्टि करें','This action changes stored data.':'यह कार्य सहेजे गए डेटा को बदलता है।','Delete permanently':'स्थायी रूप से मिटाएँ','Retry':'फिर कोशिश करें','Skip to content':'मुख्य सामग्री पर जाएँ','Sort':'क्रम','Newest':'सबसे नया','Oldest':'सबसे पुराना','Category':'श्रेणी','All':'सभी','Documents':'दस्तावेज़','Videos':'वीडियो','Downloads':'डाउनलोड','Backups':'बैकअप','Load more':'और लोड करें','Calculate':'गणना करें','Expression':'गणना','Clear':'मिटाएँ','History':'इतिहास','Verification':'सत्यापन','Receiving screen':'आने वाली स्क्रीन','Stop session':'सत्र बंद करें','Remote sessions':'रिमोट सत्र','Notifications in this app':'इस ऐप में सूचनाएँ','Setup':'सेटअप',
  'Backup interval (minutes)':'बैकअप अंतराल (मिनट)','Scrub interval (hours)':'फ़ाइल जाँच अंतराल (घंटे)','Second-copy interval (minutes)':'दूसरी कॉपी का अंतराल (मिनट)','Allow screen sharing':'स्क्रीन साझा करने दें','Request scheduled wake':'निर्धारित समय पर चालू करने का अनुरोध','Wake time':'जागने का समय','Check for signed updates':'हस्ताक्षरित अपडेट जाँचें','Update manifest URL':'अपडेट सूची का पता','Update public key':'अपडेट सार्वजनिक कुंजी'
};
export function translate(language, key) { return language === 'hi' ? hi[key] || key : key; }
